### ISSUE TITLE
sparta_wrapper_functions

### ISSUE THREAD

**Issue by EichenbergBEF** [bowlerbear/sMon-insects#1]
Concerns the annualPredictions function:
I tried it, reading in the model outputs from the amphibia data. The getSpartaModels function works fine. However, wehn submitting them to the annualPredictions function, R throws an error
" non-unique values when setting 'row.names':"
Maybe I got sth wrong. But it might be worth to try the function also on the odel outputs from the portal, which iare the ones I used and ran into this problem.

**Comment by bowlerbear** [comment]
Ok! Will have a look tomorrow!

**Comment by bowlerbear** [comment]
Should work now, as follows:
model.list<-getSpartaModels('model-outputs')
myAnnualPredictions<-annualPredictions(model.list)
head(myAnnualPredictions)
plotPredictions(myAnnualPredictions)

This file is also in the amphibian folder too

The problem was the regional codes.
It would also be possible to extract the regional variation as well for plotting.
You just have to delve into the BUGSoutput section of each model.

![amphibians](https://user-images.githubusercontent.com/9789903/35670958-e0d0598c-0731-11e8-8f13-7f3c8a13583d.png)

**Comment by EichenbergBEF** [comment]
Works now! Thank you. However, when I try to get the trends via calculateTrends, I get the error "clusure not subsettable". I dived into the code and realized that it has to do with the specification of 'firstYear' and 'lastYear' in the occurenceChange wrapper. It seems that the argument

firstYeat=min(df$Year) as well as lastYear=max(df$Year)

does not refer to what you initially had in mind. 

However, changing 'df$Year' to 'myAnnualPredictions$Year' does the job. Is this right? If so, the function needs to be adjusted to incorporate a further parameter, which is myAnnualPredictions. 
On the other hand, of course it would make more sense to find the $Year argument directly in the model outputs. However, I did not find the corresponding 'Year' entry in the model output datsets, yet.

**Comment by bowlerbear** [comment]
Oops sorry. Didnt check that bit
you can pull our first and last year from x$min_year and x$max_year
In a meeting now, will fix later if this simple fix doesnt work.

**Comment by EichenbergBEF** [comment]
No problem. I fixed it. Just some minor changes in the code, after you gave this hint.... see the lastest commit.
hey... this is fun!

**Comment by bowlerbear** [comment]
done
